---
title: "Dashboard Airbnb"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(janitor)
library(stringr)
library(forcats)
library(viridis)
library(plotly)

airbnb_data <- read_csv("../data/nyc_airbnb.zip") %>%
                clean_names() %>%
                rename(boro = neighbourhood_group) %>% 
                mutate(rating = review_scores_location / 2) %>% 
                filter(boro == "Manhattan",
                       room_type == "Entire home/apt",
                       price > 100 & price < 400)


```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}

airbnb_data %>%
  mutate(text_label = str_c("Price: $", price, '\nRating: ', rating)) %>% 
  plot_ly(x = ~longitude, y = ~latitude, type = "scatter", mode = "markers",
          alpha = 0.5, 
          color = ~price,
          text = ~text_label)


```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}

airbnb_data %>% 
  count(neighbourhood) %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) %>% 
  plot_ly(x = ~neighbourhood, y = ~n, color = ~neighbourhood, type = "bar")


```

### Chart C

```{r}

common_neighborhoods =
  airbnb_data %>% 
  count(neighbourhood, sort = TRUE) %>% 
  select(neighbourhood)
## Selecting by n

inner_join(airbnb_data, common_neighborhoods,
             by = "neighbourhood") %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) %>% 
  plot_ly(y = ~price, color = ~neighbourhood, type = "box",
          colors = "Set2")

```