---
title: "Plotly File"
author: "Angel Garcia de la Garza"
date: "11/1/2017"
output: html_document
---

```{r read_libraries}

library(tidyverse)
library(janitor)
library(stringr)
library(forcats)
library(viridis)
library(plotly)

```


```{r clean_data}

airbnb_data <- read_csv("../data/nyc_airbnb.zip") %>%
                clean_names() %>%
                rename(boro = neighbourhood_group) %>% 
                mutate(rating = review_scores_location / 2) %>% 
                filter(boro == "Manhattan",
                       room_type == "Entire home/apt",
                       price > 100 & price < 400)


```


```{r plot_map}


airbnb_data %>%
  plot_ly(x = ~longitude, y = ~latitude, type = "scatter",
                        alpha = 0.5, color = ~price)

airbnb_data %>%
  plot_ly(x = ~longitude, y = ~latitude, type = "scatter")


airbnb_data %>%
  mutate(text_label = str_c("Price: $", price)) %>% 
  plot_ly(x = ~longitude, y = ~latitude, type = "scatter", mode = "markers",
          alpha = 0.5, 
          color = ~price,
          text = ~text_label)


airbnb_data %>%
  mutate(text_label = str_c("Price: $", price, '\nRating: ', rating)) %>% 
  plot_ly(x = ~longitude, y = ~latitude, type = "scatter", mode = "markers",
          alpha = 0.5, 
          color = ~price,
          text = ~text_label)


```



```{r}

common_neighborhoods =
  airbnb_data %>% 
  count(neighbourhood, sort = TRUE) %>% 
  top_n(8) %>% 
  select(neighbourhood)
## Selecting by n

inner_join(airbnb_data, common_neighborhoods,
             by = "neighbourhood") %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) %>% 
  plot_ly(y = ~price, color = ~neighbourhood, type = "box",
          colors = "Set2")


common_neighborhoods =
  airbnb_data %>% 
  count(neighbourhood, sort = TRUE) %>% 
  select(neighbourhood)
## Selecting by n

inner_join(airbnb_data, common_neighborhoods,
             by = "neighbourhood") %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) %>% 
  plot_ly(y = ~price, color = ~neighbourhood, type = "box",
          colors = "Set2")



```


```{r counts_plot}

airbnb_data %>% 
  count(neighbourhood) %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) %>% 
  plot_ly(x = ~neighbourhood, y = ~n, color = ~neighbourhood, type = "bar")


```

```{r}

scatter_ggplot = airbnb_data %>%
  ggplot(aes(x = longitude, y = latitude, color = price)) +
  geom_point(alpha = 0.25) +
  scale_color_viridis() +
  coord_cartesian() +
  theme_classic()

ggplotly(scatter_ggplot)

```

